### ISSUE TITLE
If podnotes folder does not exist in POD then create

### ISSUE THREAD

**Issue by gjwgit** [anusii/podnotes#4]

**Comment by anushkavidanage** [comment]
Pull request https://github.com/anusii/podnotes/pull/9

**Comment by gjwgit** [comment]
The `Welcome to PODNotes` setup wizard looks great.

- [ ] Why do I need to specify `Gender`?
- [ ] Is this templated or available in the solid_auth package (or maybe solid package) so we can use it in another project?

**Comment by gjwgit** [comment]
After I entered the new pod information and click Submit I got:



![Image](https://github.com/anusii/podnotes/assets/1681429/8b332f2e-92fc-465c-9776-61de2cb74562)

and

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building TextField(controller:
TextEditingController#4a63c(TextEditingValue(text: ┤├, selection: TextSelection.invalid, composing:
TextRange(start: -1, end: -1))), focusNode: FocusNode#a0159, enabled: true, decoration:
InputDecoration(hintText: "Editable text", floatingLabelBehavior: FloatingLabelBehavior.auto,
floatingLabelAlignment: FloatingLabelAlignment.start, alignLabelWithHint: false), keyboardType:
TextInputType(name: TextInputType.multiline, signed: null, decimal: null), maxLines: null,
textCapitalization: sentences, dirty, dependencies: [MediaQuery, UnmanagedRestorationScope], state:
_TextFieldState#bea7a):
No Material widget found.
TextField widgets require a Material widget ancestor within the closest LookupBoundary.
In Material Design, most widgets are conceptually "printed" on a sheet of material. In Flutter's
material library, that material is represented by the Material widget. It is the Material widget
that renders ink splashes, for instance. Because of this, many material library widgets require that
there be a Material widget in the tree above them.
To introduce a Material widget, you can either directly include one, or use a widget that contains
Material itself, such as a Card, Dialog, Drawer, or Scaffold.
The specific widget that could not find a Material ancestor was:
  TextField
The ancestors of this widget were:
  ...
  UnmanagedRestorationScope
  TextFormField
  Expanded
  Row
  Column
  ...

The relevant error-causing widget was:
  TextFormField
  TextFormField:file:///home/gjw/.pub-cache/hosted/pub.dev/markdown_editor_plus-0.2.13/lib/widgets/splitted_markdown_form_field.dart:263:28

When the exception was thrown, this was the stack:
#0      debugCheckHasMaterial.<anonymous closure> (package:flutter/src/material/debug.dart:38:7)
#1      debugCheckHasMaterial (package:flutter/src/material/debug.dart:63:4)
#2      _TextFieldState.build (package:flutter/src/material/text_field.dart:1239:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5583:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453:5)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625:11)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447:5)
...     Normal element mounting (21 frames)
#30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#31     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#32     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883:32)
#33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#34     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#35     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883:32)
#36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:3837:18)
#38     _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:132:18)
#39     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2835:19)
#40     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:150:12)
#41     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2657:59)
#42     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1071:15)
#43     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2657:14)
#44     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:225:7)
#45     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:308:5)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#47     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#50     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#53     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#56     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#57     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:238:12)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#59     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#60     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#61     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:808:43)
#62     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903:32)
#63     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#64     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#65     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#66     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#67     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#68     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#69     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#70     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#72     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#73     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#74     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#75     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#76     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#78     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#79     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#80     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#81     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#82     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#84     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#85     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#86     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#87     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#88     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#89     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#90     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#91     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#92     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3712:14)
#93     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#94     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#95     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#96     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#97     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#98     _RenderTheaterMixin.performLayout (package:flutter/src/widgets/overlay.dart:884:15)
#99     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2385:7)
#100    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1025:18)
#101    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1038:15)
#102    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591:23)
#103    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986:13)
#104    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#105    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#106    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#107    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#108    _invoke (dart:ui/hooks.dart:312:13)
#109    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#110    _drawFrame (dart:ui/hooks.dart:283:31)

════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: No Material widget found.
Another exception was thrown: No Material widget found.
Another exception was thrown: No Material widget found.
Another exception was thrown: No Material widget found.
Another exception was thrown: A RenderFlex overflowed by 99397 pixels on the bottom.
```

**Comment by gjwgit** [comment]
When I log in again I get this error:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Namespace https is used but not defined. (caused by https://solidcommunity.au/predicates/personal#Gender-Male)
#0      Graph.item (package:rdflib/src/graph.dart:693:9)
#1      Graph._saveToGroups (package:rdflib/src/graph.dart:612:32)
#2      Graph.parseTurtle (package:rdflib/src/graph.dart:581:7)
#3      getFileContent (package:podnotes/common/rdf_functions.dart:6:5)
#4      LoginScreen.createSolidLoginRow.<anonymous closure> (package:podnotes/login/login_screen.dart:193:32)
<asynchronous suspension>
```

**Comment by gjwgit** [comment]
Noting that the functionality is now working on my testing.

Requires coding style and warning updates.
