### ISSUE TITLE
BUG: When sharing in Linux/Web/macos it hangs

### ISSUE THREAD

**Issue by jesscmoore** [anusii/podnotes#74]
![Image](https://github.com/anusii/podnotes/assets/1681429/f0a38216-205d-4dbe-8c65-25cae4695d98)

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Failed to load data! Try again in a while.
#0      fetchPubFile (package:podnotes/common/rest_api/rest_api.dart:280:5)
<asynchronous suspension>
#1      checkPublicProf (package:podnotes/common/rest_api/res_permission.dart:272:21)
<asynchronous suspension>
#2      addPermission (package:podnotes/common/rest_api/res_permission.dart:107:9)
<asynchronous suspension>
#3      _ShareNoteState._displayPermissionInputDialog.<anonymous closure>.<anonymous closure> (package:podnotes/notes/share_note.dart:588:17)
<asynchronous suspension>

Lost connection to device.
```

**Comment by jesscmoore** [comment]
This occurs in macos also.

**Comment by jesscmoore** [comment]
Closing as this problem no longer occurs.
