### ISSUE TITLE
VIEW NOTE: select note causing Null check operator used on a null value

### ISSUE THREAD

**Issue by jesscmoore** [anusii/podnotes#88]
In karen-reep pod:

My Notes > click any note card: is causing `Null check operator used on a null value` red screen error, preventing the selected note from displaying

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _TypeError was thrown building FutureBuilder<dynamic>(dirty, state:
_FutureBuilderState<dynamic>#e3e40):
Null check operator used on a null value

The relevant error-causing widget was:
  FutureBuilder<dynamic>
  FutureBuilder:file:///Users/u9904893/Documents/podnotes/lib/notes/view_edit_note_screen.dart:97:16

When the exception was thrown, this was the stack:
#0      _ViewEditNoteScreenState.build.<anonymous closure> (package:podnotes/notes/view_edit_note_screen.dart:103:32)
#1      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:609:55)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:5592:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904:19)
#7      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989:21)
#8      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#10     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#11     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#12     _invoke (dart:ui/hooks.dart:312:13)
#13     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:382:5)
#14     _drawFrame (dart:ui/hooks.dart:283:31)

**Comment by gjwgit** [comment]
Seems to no longer be an issue.
